In [1]:
import gym 
import numpy as np 

In [2]:
env = gym.make("FrozenLake-v0")

In [3]:

Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000

rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [5]:
print( str(sum(rList)/num_episodes))


0.413


In [6]:
print(Q)

[[2.26264074e-01 5.49186024e-03 5.91680811e-03 6.74308206e-03]
 [1.11845285e-03 2.29224553e-04 1.83413000e-06 4.06023064e-02]
 [8.47409993e-04 9.49784181e-04 1.38304502e-03 5.13994017e-02]
 [4.22959577e-04 2.44304199e-05 3.55780554e-05 5.99123772e-02]
 [3.54905398e-01 1.09481116e-04 9.50176421e-04 1.32644798e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.03044457e-03 1.85393548e-05 1.02631959e-03 4.30700589e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.11628363e-03 2.97765450e-04 1.07436549e-03 3.22865217e-01]
 [8.36353286e-04 5.76941850e-01 7.88483874e-04 9.15406970e-04]
 [5.63577703e-02 8.25196543e-04 3.67148673e-04 5.63244284e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [2.13559621e-03 2.77078870e-04 8.48403010e-01 5.57716372e-04]
 [0.00000000e+00 0.00000000e+00 3.41229498e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.000000